# Generated by Django 5.2.5 on 2025-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fly", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
