# Generated by Django 5.2.5 on 2025-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fly", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
